/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_szu_refrigerator_nativelib_ObjectDetectorNative */

#ifndef _Included_com_szu_refrigerator_nativelib_ObjectDetectorNative
#define _Included_com_szu_refrigerator_nativelib_ObjectDetectorNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_szu_refrigerator_nativelib_ObjectDetectorNative
 * Method:    destroyInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_szu_refrigerator_nativelib_ObjectDetectorNative_destroyInternal
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_szu_refrigerator_nativelib_ObjectDetectorNative
 * Method:    initInternal
 * Signature: ([BI)J
 */
JNIEXPORT jlong JNICALL Java_com_szu_refrigerator_nativelib_ObjectDetectorNative_initInternal
        (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_szu_refrigerator_nativelib_ObjectDetectorNative
 * Method:    detectInternal
 * Signature: (J[B)[Lcom/szu/refrigerator/nativelib/DetectionResult;
 */
JNIEXPORT jobjectArray JNICALL Java_com_szu_refrigerator_nativelib_ObjectDetectorNative_detectInternal
        (JNIEnv *, jobject, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
