// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: fridge.proto
#ifndef GRPC_fridge_2eproto__INCLUDED
#define GRPC_fridge_2eproto__INCLUDED

#include "fridge.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace AN {

class ObjectDetector final {
 public:
  static constexpr char const* service_full_name() {
    return "AN.ObjectDetector";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientWriterInterface< ::AN::ImageChunk>> DetectImage(::grpc::ClientContext* context, ::AN::DetectResult* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::AN::ImageChunk>>(DetectImageRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::AN::ImageChunk>> AsyncDetectImage(::grpc::ClientContext* context, ::AN::DetectResult* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::AN::ImageChunk>>(AsyncDetectImageRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::AN::ImageChunk>> PrepareAsyncDetectImage(::grpc::ClientContext* context, ::AN::DetectResult* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::AN::ImageChunk>>(PrepareAsyncDetectImageRaw(context, response, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void DetectImage(::grpc::ClientContext* context, ::AN::DetectResult* response, ::grpc::ClientWriteReactor< ::AN::ImageChunk>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientWriterInterface< ::AN::ImageChunk>* DetectImageRaw(::grpc::ClientContext* context, ::AN::DetectResult* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::AN::ImageChunk>* AsyncDetectImageRaw(::grpc::ClientContext* context, ::AN::DetectResult* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::AN::ImageChunk>* PrepareAsyncDetectImageRaw(::grpc::ClientContext* context, ::AN::DetectResult* response, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientWriter< ::AN::ImageChunk>> DetectImage(::grpc::ClientContext* context, ::AN::DetectResult* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::AN::ImageChunk>>(DetectImageRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::AN::ImageChunk>> AsyncDetectImage(::grpc::ClientContext* context, ::AN::DetectResult* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::AN::ImageChunk>>(AsyncDetectImageRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::AN::ImageChunk>> PrepareAsyncDetectImage(::grpc::ClientContext* context, ::AN::DetectResult* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::AN::ImageChunk>>(PrepareAsyncDetectImageRaw(context, response, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void DetectImage(::grpc::ClientContext* context, ::AN::DetectResult* response, ::grpc::ClientWriteReactor< ::AN::ImageChunk>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientWriter< ::AN::ImageChunk>* DetectImageRaw(::grpc::ClientContext* context, ::AN::DetectResult* response) override;
    ::grpc::ClientAsyncWriter< ::AN::ImageChunk>* AsyncDetectImageRaw(::grpc::ClientContext* context, ::AN::DetectResult* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::AN::ImageChunk>* PrepareAsyncDetectImageRaw(::grpc::ClientContext* context, ::AN::DetectResult* response, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_DetectImage_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status DetectImage(::grpc::ServerContext* context, ::grpc::ServerReader< ::AN::ImageChunk>* reader, ::AN::DetectResult* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_DetectImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DetectImage() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_DetectImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DetectImage(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::AN::ImageChunk>* /*reader*/, ::AN::DetectResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDetectImage(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::AN::DetectResult, ::AN::ImageChunk>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_DetectImage<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_DetectImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DetectImage() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::AN::ImageChunk, ::AN::DetectResult>(
            [this](
                   ::grpc::CallbackServerContext* context, ::AN::DetectResult* response) { return this->DetectImage(context, response); }));
    }
    ~WithCallbackMethod_DetectImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DetectImage(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::AN::ImageChunk>* /*reader*/, ::AN::DetectResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::AN::ImageChunk>* DetectImage(
      ::grpc::CallbackServerContext* /*context*/, ::AN::DetectResult* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_DetectImage<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_DetectImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DetectImage() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_DetectImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DetectImage(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::AN::ImageChunk>* /*reader*/, ::AN::DetectResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_DetectImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DetectImage() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_DetectImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DetectImage(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::AN::ImageChunk>* /*reader*/, ::AN::DetectResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDetectImage(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DetectImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DetectImage() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, ::grpc::ByteBuffer* response) { return this->DetectImage(context, response); }));
    }
    ~WithRawCallbackMethod_DetectImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DetectImage(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::AN::ImageChunk>* /*reader*/, ::AN::DetectResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* DetectImage(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace AN


#endif  // GRPC_fridge_2eproto__INCLUDED
